### ISSUE TITLE
bug: Members are not ordered by explicit list

### ISSUE THREAD

**Issue by RafaelWO** [mkdocstrings/python#119] opened 2023-12-27 15:29 UTC
### Description of the bug
Hello, I'm trying to display some members of a module in a specific order. For that, I have the following block in my Markdown file:

```
::: mymodule
    options:
      members:
      - my_func
      - MyData
```

The documentation on the `members` option says:

> The members will be rendered in the specified order, regardless of the value of `members_order`. [[source](https://mkdocstrings.github.io/python/usage/configuration/members/#members)]

But when rendering the page with mkdocs, the member `MyData` is displayed first:

![grafik](https://github.com/mkdocstrings/python/assets/38643099/f42b10f2-dc13-47ae-a9ca-bfb7185fdcdf)

### To Reproduce

[members_order_test.zip](https://github.com/mkdocstrings/python/files/13779521/members_order_test.zip)

```
I have compiled a MRE example and attached it as a zip file above. The contents are as follows:

test
├── docs
│   └── index.md
├── mkdocs.yml
├── mymodule
│   └── __init__.py
└── requirements.txt

1. Download it and extract the files
2. Run `cd test`
3. Run `pip install -r requirements.txt`
4. Run `mkdocs serve`
5. Open http://127.0.0.1:8000/ in a browser
6. You should see the same result as in the screenshot above
```

### Full traceback

n/a

### Expected behavior
I would expected that `mymodule.my_func` is displayed first.

### Environment information

```bash
python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
```
- __System__: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- __Python__: cpython 3.11.5
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.5.3
  - `mkdocstrings` v0.24.0
  - `mkdocstrings-python` v1.7.5
  - `griffe` v0.38.1

### Additional context

n/a

**Comment by pawamoy** [comment] 2024-01-09 14:43
Hello, thanks for the report!

So, I think it works as intended, however there's a subtlety that should definitely be documented to avoid confusion: objects are still grouped by category (modules, classes, functions, attributes) before being sorted as specified by `members` or `members_order`. Can you try disabling grouping to see if it solves your issue? [`group_by_category: false`](https://mkdocstrings.github.io/python/usage/configuration/members/#group_by_category).

**Comment by pawamoy** [comment] 2024-01-09 14:58
I was able to confirm my suggested solution above in your MRE (thanks for it). I pushed an update to the docs, will deploy them now, closing :slightly_smiling_face:

**Closed by pawamoy** 2024-01-09 14:58 UTC
Labels: documentation

**Comment by RafaelWO** [comment] 2024-01-12 08:13
Thanks for the explanation and the update to the docs! It's much clearer now 🙂
