### ISSUE TITLE
bug: `show_symbol_type_toc` not working with newest version of Python handler / material theme

### ISSUE THREAD

**Issue by femtomc** [mkdocstrings/python#158] opened 2024-05-03 14:31 UTC
Hi!

### Description of the bug
I'm using the newest insider's edition of `mkdocstrings-python`, and I'm attempting to use:

```
plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      handlers:
        python:
          options:
            show_symbol_type_toc: true
```

in my documentation (with an admittedly old insider's edition of `mkdocs-material`). However, the symbols are not rendering in the side ToC.

### Expected behavior
I expect the symbol types to show up next to the entries in the side ToC.

### Environment information

Here's my exact versioning:

```
mkdocs                                    1.5.3
mkdocs-autorefs                           1.0.1
mkdocs-git-authors-plugin                 0.7.2
mkdocs-git-committers-plugin-2            1.2.0
mkdocs-git-revision-date-localized-plugin 1.2.5
mkdocs-material                           9.5.4+insiders.4.49.2
mkdocs-material-extensions                1.3.1
mkdocstrings                              0.25.0
mkdocstrings-python                       1.10.0.1.8.2.dev19+g995e505
```

### Additional context

Now, I do have some errors in my documentation -- but all other `mkdocstrings-python` options work correctly (e.g. `show_symbol_type_heading` works fine) and I can switch them on and off and build my documentation without issue.

**Comment by pawamoy** [comment] 2024-05-03 15:35
Try to upgrade your mkdocs-material dependency :slightly_smiling_face:

**Comment by femtomc** [comment] 2024-05-03 16:58
haha, of course! thank you, sorry for the time waste

**Comment by pawamoy** [comment] 2024-05-03 17:07
No problem! Thanks for trying this so quickly :smile:

**Comment by femtomc** [comment] 2024-05-04 17:58
@pawamoy Unfortunately, still encountering this with the following (up-to-date) dependencies:

```
mkdocs-material                           9.5.21+insiders.4.53.8
mkdocs-material-extensions                1.3.1
mkdocstrings                              0.25.0
mkdocstrings-python                       0.1.dev395+g995e505
```

Here's my full plugin config:
```
plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      handlers:
        python:
          options:
            show_symbol_type_toc: true
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_symbol_type_heading: true
            parameter_headings: true
            separate_signature: true
            signature_crossrefs: true
            show_signature_annotations: true
```

**Comment by pawamoy** [comment] 2024-05-04 18:03
Oh OK, I should you confirmed the upgrade fixed the issue. I'll try to replicate.

mkdocstrings-python 0.1.dev395+g995e505: I guess you're installing with git+(https/ssh), from main branch? Try installing from latest tag instead.

**Comment by femtomc** [comment] 2024-05-04 18:17
Okay, will try this now!

**Comment by femtomc** [comment] 2024-05-04 18:25
Can reproduce same issue with my docs with:

```
mkdocs-material                           9.5.21+insiders.4.53.8
mkdocs-material-extensions                1.3.1
mkdocstrings                              0.25.0
mkdocstrings-python                       1.10.0.1.8.1
```

I believe that's the last tagged release of `mkdocstrings-python`

**Comment by pawamoy** [comment] 2024-05-04 20:12
Thanks for your patience! I'll be able to verify in an hour or so :)

**Comment by pawamoy** [comment] 2024-05-04 21:15
I cannot reproduce the issue :confused: 

I tried with these dependencies:

```
Markdown==3.6
markdown-callouts==0.4.0
markdown-exec==1.7.0.1.0.1
markdown-it-py==3.0.0
mkdocs==1.6.0
mkdocs-autorefs==1.0.1
mkdocs-coverage==1.0.0
mkdocs-gen-files==0.5.0
mkdocs-get-deps==0.2.0
mkdocs-git-committers-plugin-2==2.3.0
mkdocs-literate-nav==0.6.1
mkdocs-material==9.5.19+insiders.4.53.7
mkdocs-material-extensions==1.3.1
mkdocs-minify-plugin==0.8.0
mkdocstrings==0.25.0
mkdocstrings-python==1.10.0.1.8.1
```

...as well as `mkdocs-material==9.5.21+insiders.4.53.8` (latest), and in both cases, symbols in the ToC showed up.

**Comment by pawamoy** [comment] 2024-05-04 21:19
If your repository is public, don't hesitate to share it so I can see for myself :slightly_smiling_face: This will allow us to confirm if this is an environment issue.

**Comment by femtomc** [comment] 2024-05-05 10:11
@pawamoy I can invite you to the repo! I think you've helped me out before in this way in the past (thanks for that!) -- if you don't mind doing this, let me know

**Comment by pawamoy** [comment] 2024-05-05 13:39
Ah, found the issue. I was going insane but it's actually a very simple bug: I wrongly recurse into heading tokens only when a parent heading has its label set by mkdocstrings. When top-level headings are not mkdocstrings headings, it fails, because I never descend into the other headings.

Will push a fix right now :smile: Thanks for your patience again and for giving me access to your repo where the issue was reproducible :blush:

**Comment by femtomc** [comment] 2024-05-05 13:49
Cool! Awesome that you found the issue, and no problem!

**Comment by pawamoy** [comment] 2024-05-05 14:25
Version 0.25.1 of mkdocstrings is out :)

**Comment by femtomc** [comment] 2024-05-05 14:26
Thanks for a rapid response!

**Comment by pawamoy** [comment] 2024-05-05 14:38
Closing, let me know if you have any issue :slightly_smiling_face: Don't forget to remove me from your project ^^

**Closed by pawamoy** 2024-05-05 14:38 UTC
