### ISSUE TITLE
Properties are rendered with parens

### ISSUE THREAD

**Issue by bear24rw** [mkdocstrings/python#9] opened 2022-03-22 22:29 UTC
**Describe the bug**
`@property`'s are rendered with trailing `()` which makes them look like functions.

**To Reproduce**
```
class Example:
    @property
    def foobar(self):
        """
        Return the value of the foobar property
        """
        return 42
```
**Expected behavior**
I expect the heading in the API docs to be just `foobar` but it is rendered as `foobar()`

**System (please complete the following information):**
```
mkdocs==1.2.3
mkdocs-autorefs==0.4.1
mkdocs-material==7.3.4
mkdocs-material-extensions==1.0.3
mkdocstrings==0.18.1
mkdocstrings-python==0.6.6
```

**Comment by pedrolabonia** [comment] 2022-04-15 20:33
Since the new griffe version creates labels, should we do it on the templating side? We can do a simple check to see if the `Function` object passed by griffe has ` 'property' in object.labels`.

I don't know if this can be solved directly on the Jinja template or if we need additional context from Griffe.

If we could have some direction I can try to help.

**Comment by pawamoy** [comment] 2022-04-15 23:22
You guessed right! I was exactly planning to add a check in the templates :slightly_smiling_face: I'm glad to hear you're working on it, should I wait for a PR then :smile: ?

**Comment by pedrolabonia** [comment] 2022-04-15 23:28
> You guessed right! I was exactly planning to add a check in the templates 🙂 I'm glad to hear you're working on it, should I wait for a PR then 😄 ?

Yes!

Also, one question... Right now, @property getters and setters are marked as functions, and you've wrote tests do assert so.

Do you want to keep that design, or should we pass them as attributes from griffe?

Just thinking about "economy" of code here, since griffe is telling all themes it's a function, and we'd need to adjust every theme.

**Comment by pawamoy** [comment] 2022-04-16 08:41
Griffe will always return a property as a function. That's just how it is technically. But when rendering API documentation, it makes sense to categorize them as attributes, since that's how they are used.

**Comment by pedrolabonia** [comment] 2022-04-16 09:59
I agree that passing them as attributes from Griffe might be the best way. I can't imagine right now a use case where a property would be bundled with the class methods, but there might be some edge cases.

Doing it in Griffe avoids all the templating patching and logic for that specific case, and feels to me as more of an expected behavior.

If you have any ideas on how to go about this, I can try to help. I'll close the PR for now.

**Comment by pawamoy** [comment] 2022-04-16 11:29
> Doing it in Griffe avoids all the templating patching and logic for that specific case, and feels to me as more of an expected behavior.

Exactly!

> If you have any ideas on how to go about this, I can try to help.

Let me bring the change in Griffe, then I'll give you some guidance to update the Python handler :slightly_smiling_face:

**Comment by cory-kinney** [comment] 2022-10-11 13:58
Just wondering if there has been any progress on rendering properties as attributes; I'm generating some documentation with quite a few properties and don't want anyone to be confused by them looking like functions.

**Comment by pawamoy** [comment] 2022-11-30 23:06
This is now implemented and will be published with the next release of Griffe.

**Closed by pawamoy** 2022-11-30 23:06 UTC
