### ISSUE TITLE
bug: Test suite is failing while running with Python 3.12 in Debian

### ISSUE THREAD

**Issue by tijuca** [mkdocstrings/python#121] opened 2024-01-12 06:21 UTC
### Description of the bug
Since the introduction of Python 3.12 the test suite of mkdocstrings-python is failing, running the same tests with 3.11 no problems are visible.

There is a [bug report #1058340](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1058340) opened about this issue. I'm not deep enough within the code the relationships to solve this issue, for now it's looks to me that some Python 3.12 related changes come to play here.

But not only rebuilding the package currently fails, also ruining the tests within the CI for running such autopkgtests shows this issues for possible Debian architecture in the suite unstable.
https://ci.debian.net/packages/m/mkdocstrings-python-handlers/

A short and quick view, the issue is basically looking like this.

```
> ______ ERROR at setup of test_render_docstring_examples_section[handler2] ______
> 
> request = <SubRequest 'handler' for <Function test_render_docstring_examples_section[handler2]>>
> tmp_path = PosixPath('/tmp/pytest-of-user42/pytest-21/test_render_docstring_examples2')
> 
>     @pytest.fixture(name="mkdocs_conf")
>     def fixture_mkdocs_conf(request: pytest.FixtureRequest, tmp_path: Path) -> Iterator[config.Config]:
>         """Yield a MkDocs configuration object.
>     
>         Parameters:
>             request: Pytest fixture.
>             tmp_path: Pytest fixture.
>     
>         Yields:
>             MkDocs config.
>         """
>         conf = MkDocsConfig()
>         while hasattr(request, "_parent_request") and hasattr(request._parent_request, "_parent_request"):
>             request = request._parent_request
>     
>         conf_dict = {
>             "site_name": "foo",
>             "site_url": "https://example.org/",
>             "site_dir": str(tmp_path),
>             "plugins": [{"mkdocstrings": {"default_handler": "python"}}],
>             **getattr(request, "param", {}),
>         }
>         # Re-create it manually as a workaround for https://github.com/mkdocs/mkdocs/issues/2289
>         mdx_configs: dict[str, Any] = dict(ChainMap(*conf_dict.get("markdown_extensions", [])))
>     
>         conf.load_dict(conf_dict)
> >       assert conf.validate() == ([], [])
> E       assert ([('theme', V...edocs"))], []) == ([], [])
> E         At index 0 diff: [('theme', ValidationError("Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs"))] != []
> E         Use -v to get more diff
> 
> tests/conftest.py:47: AssertionError
> _ ERROR at setup of test_render_themes_templates_python[mkdocstrings.extension-plugin2] _
```

What makes me wonder is simply that the same tests in the same environment are running successfully with a Python 3.11 interpreter, but not with 3.12. The let me for now conclude that the problem is more related to the changes that are made within Python 3.12.

I tried to import and package the recent version 1.8.0, but the (error message) output is in principle the same.

I'm happily taking any advise or hint to get this issue solved, thanks!

**Comment by pawamoy** [comment] 2024-01-12 14:57
Thanks for the report.

It looks like the `mkdocs-material` Python dependency is missing when running the tests. From looking at the logs, I don't see any command that tries to install it? I'm not sure how previous build would not fail without `mkdocs-material`.

**Comment by tijuca** [comment] 2024-01-12 17:51
> EDIT: now looking at more complete logs, I see that `mkdocs-material` is installed (along with others packages like python3-griffe, not sure what warrants the python3- prefix or not), so I'm not sure why the tests do not find it when on Python 3.12, when they do find it while on Python 3.11

Yes, that's also my thinking, why do the test get running successfully with 3.11 but not with 3.12.

The Python 3 based packages in Debian are prefixed simply because as we did also have not that long ago Python 2 based packages that there prefixed with `python-` in the archive, that mainly a thing to make visible which Python version the package targeted for.

Maybe we can find more if you can tell me what pragmatically can get added to some files as print() statement so we can find out there the code is trying to find something. To me it looks like that for whatever reason the required theme can't be found. It's also possible that other Debian packages (mkdocs-material?) might have some packaging issues that are now getting visible through Python 3.12.

**Comment by pawamoy** [comment] 2024-01-13 19:59
I'd say it's a packaging issue indeed. When installed, themes are exposed to MkDocs with the standard "entry points" metada, see https://www.mkdocs.org/dev-guide/themes/#package-layout. So if the Debian package `mkdocs-material` is installed, but MkDocs does not detect it, it's an issue between these two packages. I'll give you some locations where to add print statement later :)

**Comment by s3v-** [comment] 2024-01-18 11:03
Hi,
Maybe the problem is that mkdocs-material push all the stuff in the wrong directory:
https://packages.debian.org/sid/all/mkdocs-material/filelist

Thanks for all your work!

**Comment by hosiet** [comment] 2024-02-02 02:29
I would say this is 100% a packaging issue. Not sure about the correct solution yet.

Downstream packaging bug report: https://bugs.debian.org/1062582

**Comment by tijuca** [comment] 2024-02-02 07:34
Thanks all for the input, due $(private_life) I was not able to work further on this in the past weeks. But yes, in the past I was digging into the `mkdoc-material` packaging for other reasons and and found also some potential issues with the kind it is(was) packaged.

**Comment by pawamoy** [comment] 2024-02-02 12:29
Thanks for the hint and link @s3v-, @hosiet. Since it's a Debian packaging issue, there's nothing we can do here, so I'll close this issue. Thanks everyone for the help!

**Closed by pawamoy** 2024-02-02 12:29 UTC
