### ISSUE TITLE
bug: broken crossref links when the field name matches type name

### ISSUE THREAD

**Issue by cmclaughlin** [mkdocstrings/python#202] opened 2024-11-03 23:25 UTC
First of all, I'm only a couple days into using mkdocstrings. It's really nice... thanks for the nice work!

### Description of the bug
Although it might not be "best practice" if a class field name matches the type of the field, signature_crossrefs generate a broken link. 

### To Reproduce

I put together this example:

https://github.com/cmclaughlin/mkdocstrings-crossref-fieldname-bug

Here's how to set it up.
```
# create and activate your own venv...
git clone https://github.com/cmclaughlin/mkdocstrings-crossref-fieldname-bug
cd mkdocstrings-crossref-fieldname-bug
pip install -e .
mkdocs serve
```

I also published the output here as a live demo:

http://mkdocstrings-fieldname-crossref-issue.s3-website-us-west-2.amazonaws.com/

Note: that's http, not https so you will probably need to accept a warning in your browser

### Expected behavior
Please see "1 working example" on the demo I put together. That shows the crossrefs working as I expect.
Then see "2 broken example" to see how it's not working as expected when the field name matches the type.

### Environment information

```bash
$ python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
- __System__: macOS-14.5-arm64-arm-64bit-Mach-O
- __Python__: cpython 3.13.0 (/Users/cmclaughlin/.pyenv/versions/mkdocstrings-crossref-fieldname-bug/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.1
  - `mkdocstrings` v0.26.2
  - `mkdocstrings-python` v1.12.2
  - `griffe` v1.5.1
```

I also just joined the insiders org to try the newer version...

```
$ python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
- __System__: macOS-14.5-arm64-arm-64bit-Mach-O
- __Python__: cpython 3.13.0 (/Users/cmclaughlin/.pyenv/versions/mkdocstrings-crossref-fieldname-bug-insiders/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.1
  - `mkdocstrings` v0.26.2
  - `mkdocstrings-python` v1.12.2.1.9.0
  - `griffe` v1.5.1
 ```

### Additional context

This issue is similar:
https://github.com/microsoft/pyright/issues/3924

Following the suggestions from that issue, I tried adding `from __future__ import annotations` to my classes in the example, but it didn't resolve the problem.

As I mentioned above, I tried joining the insider org to get the newest version. I tried the `relative_crossrefs` and `scoped_crossrefs` features. I'm not sure if either of those are really what I want - I'd rather not have to change the docstrings if possible.

Also I hope this is the right place for this issue. Maybe this bug (if you agree it is a bug) is in griffe? 

Thanks

**Comment by cmclaughlin** [comment] 2024-11-04 01:55
I went ahead and changed my field names... so maybe best to close this issue as "wont fix".

**Comment by pawamoy** [comment] 2024-11-04 14:13
Hi @cmclaughlin, thank you for the sponsorship! And thanks for the bug report and reproduction :slightly_smiling_face: 

So indeed when Griffe sees this code:

```python
from package.tag import Tag

class MixedExamples:
    """ In this example, the two crossrefs from the working example no longer work while in the same class as the broken example """

    tag: Tag
    """ ... """

    tags: list[Tag]
    """ ... """

    Tag: Tag
    """ ... """
```

...`Tag` is resolved in the class scope, resolving to `package.MixedExample.Tag` instead of `package.tag.Tag`.

It works at runtime because `MixedExample.Tag` is actually not assigned, therefore not shadowing the outer scope `Tag` object, and even if it was assigned, it would be assigned after the first two fields are declared and annotated.

```pycon
>>> MyType = str
>>> 
>>> class MyClass:
...     field1: MyType
...     MyType: int
...     field2: MyType
...     MyType: type = float
...     field3: MyType = 0.1
... 
>>> from typing import get_type_hints
>>> get_type_hints(MyClass)
{'field1': <class 'str'>, 'MyType': <class 'float'>, 'field2': <class 'str'>, 'field3': <class 'float'>}
```

As we can see, `field1` and `field2` retain their `str` type, while `field3` is now a float, since `MyType` was re-assigned in between.

But Griffe doesn't work like the runtime, and only stores `Tag` as annotation for both fields, and then later tries to resolve it in the class' scope. That's because postponed annotations might not be resolvable immediately (not yet defined), so Griffe defers resolution to later. We could consider trying to support that by storing some additional scoping data, but that sounds like a lot of work to support a dynamic use-case (names being shadowed at some point in the flow, at import time), so I don't think we will. Therefore yes, I'd recommend avoiding such name-shadowing :slightly_smiling_face:

**Comment by pawamoy** [comment] 2024-11-04 14:38
I'll close as won't fix for the same reasons as the ones mentioned in the Pyright ticket (even though they managed to fix it somehow): scoping rules and resolution of type annotations might (have) change(d) in the next versions of Python.

I added a `docs` label to remember to document this limitation :slightly_smiling_face:

**Closed by pawamoy** 2024-11-04 14:38 UTC
Labels: docs
